### ISSUE TITLE
install error: gyp ERR!

### ISSUE THREAD

**Issue by aditakacs** [DanielRamosAcosta/aura-sdk#4] opened 2019-12-22 12:27 UTC
cmd output:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\aura-sdk
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aura-sdk@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aura-sdk@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adam\AppData\Roaming\npm-cache\_logs\2019-12-22T12_00_01_198Z-debug.log

What should be the problem?

**Comment by aditakacs** [comment] 2019-12-22 12:28
PS C:\Program Files\nodejs> node -v
v12.14.0
PS C:\Program Files\nodejs> npm -v
6.13.4
PS C:\Program Files\nodejs> node-gyp -v
v5.0.7

**Comment by SpEaGs** [comment] 2020-02-08 00:38
The whole stack trace isn't visible in your post, but this is likely caused by having the wrong or no version of Python. This is an issue with node-gyp, not with aura-sdk. You'll have to do the following to fix it:
1) Download [Python 2](https://www.python.org/downloads/release/python-2717/) and install it wherever
2) Add its filepath to your path EV (google if you don't know how),
3) Rename `python.exe` in the new install to something like `python2.exe` (only necessary if you have Python 3 already but I'd recommend doing it anyway)
4) Then in any terminal do `npm config set python python2` to tell npm which python exe to use and your issue should be fixed.

It should be noted that Python 2 is no longer getting updates as of the end of 2019, and node-gyp has been outdated for a while now since it still requires Python 2 to function properly, so it would be best to avoid these when possible. 

If you have Python 3 installed already I'd recommend renaming its exe as well so that you can call either one without things getting confusing.

Edit: Grammar

**Closed as completed** 2024-04-10 12:57 UTC
